# Generated by Django 3.1.1 on 2020-10-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='enquiry',
            field=models.TextField(editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(editable=False, max_length=254),
        ),
    ]
