# Generated by Django 3.1.1 on 2020-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201030_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry', models.TextField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
