# Generated by Django 3.1.1 on 2020-11-02 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_messages_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
