# Generated by Django 3.1.1 on 2020-11-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20201104_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Contact',
        ),
    ]
