# Generated by Django 3.1.1 on 2020-09-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_colour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.colour'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.material'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
