# Generated by Django 3.1.1 on 2020-09-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200925_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='origonal_bag',
            new_name='original_bag',
        ),
    ]
