# Generated by Django 3.1.1 on 2020-11-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_colour',
        ),
    ]
