# Generated by Django 3.1.1 on 2020-11-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_has_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://image.flaticon.com/icons/svg/38/38645.svg', upload_to=''),
        ),
    ]
